apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ .Chart.Name }}-ui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-ui
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9091
          env:
            - name: POSTGRESHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESHOST
            - name: POSTGRESPORT
              value: {{ .Values.env.POSTGRESPORT | quote }}
            - name: POSTGRESUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESUSER
            - name: POSTGRESPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESPASSWORD
            - name: POSTGRESDB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRESDB
          resources:
            requests:
              memory: '128Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '1000m'