name: Semver Build and Publish DockerHub
# Action will add tag depending on the Pull Request label (major, minor, patch , skip-release)
# Will push image to docker hub (master branch) and produce tags: `latest` and tag e.g. `0.0.1`
# Images will be produced both for AMD and ARM chips
on:
  pull_request:
    types: [ closed ]

jobs:
  semver_push_dockerhub:
    permissions:
      contents: write
    name: Semver tag and push AMD and ARM to GitHub
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      ##### Semantically tag repository and return given tag
      # Label can be : major,minor,patch or skip-release
      - name: Parse the SemVer label (semver)
        id: label
        uses: UKHomeOffice/match-label-action@v1
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value (semver)
        id: calculate
        uses: UKHomeOffice/semver-calculate-action@v1
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: true

      - name: Tag Repository (semver)
        uses: UKHomeOffice/semver-tag-action@v3
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          move_major_tag: ${{ inputs.moveMajor || 'true' }}

      - name: Publish image to Docker
        uses: UKHomeOffice/sas-github-workflows/.github/actions/docker-publish@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER_NAME || secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.QUAY_ROBOT_TOKEN }}
          tag: ${{ steps.calculate.outputs.version }}
          tag_latest: ${{ github.base_ref == 'master' }}
          image: sever3d/springboot-api-demo


      # Will create image tags `latest` and TAG from semver tagging for db migrations repository
      - name: Build and Push DB MIGRATION
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./db/Dockerfile
          push: true
          tags: |
            docker.io/sever3d/springboot-api-demo-database:${{ steps.calculate.outputs.version }}
            docker.io/sever3d/springboot-api-demo-database:latest
          platforms: linux/amd64,linux/arm64


